name: 'Slack Deploy Alert Action'
description: 'Action template for slack deploy alert'
author: 'jambam <jambam-cho@github.com>'
inputs:
  app_name:
    required: true
    description: 'application name'
  channel:
    required: true
    description: 'slack channel'
  release_version:
    required: true
    description: 'release version'
  milestones:
    required: true
    description: 'milestones for release version'
  driver:
    required: false
    description: 'The Person driving deploy'
  description:
    required: false
    description: 'description'
  app_profile:
    required: false
    description: 'application environment'
runs:
  using: 'node12'
  main: 'dist/index.js'